name: DVC Push to AWS S3

on:
  push:
    branches:      
      - main  # O la rama que uses

jobs:
  dvc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install DVC with S3 support
        run: pip install 'dvc[s3]'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: DVC Push only if .dvc files changed
        run: |
          if git diff --name-only HEAD~1 HEAD | grep '.dvc'; then
            echo "Cambios detectados en archivos .dvc, ejecutando dvc push..."
            dvc push
          else
            echo "No hay cambios en archivos .dvc, no se ejecuta dvc push."
          fi
